menu:
  主页: /
  全部文章: /archives
  学习经历: /#education
  GitHub:
    url: https://github.com/GhostDragon9889
    target: blank


cover:
  enable: true
  path: /images/cover1.jpg
  logo: false                # 封面 Logo 图片路径，不需要设为 false

mathjax: false

katex:
  enable: false
  allpost: true               # false: 仅 front-matter 中 math:true 的文章开启
  copy_tex: false


subtitle:
  enable: false
  text: 保持好奇，让想法生长。
  text2:
  text3:
  startDelay: 1000
  typeSpeed: 200
  loop: true
  backSpeed: 100
  showCursor: true

favicon: /favicon.svg        # 浏览器标签页图标
logo: /favicon.svg           # 侧边栏顶部 Logo

progressBar: false

search: false




broadcast:
  enable: false
  type: 2                    # 1: 自定义文字；2: 一言 API (hitokoto.cn)
  text: 自定义告示内容        # type 为 1 时有效

darkmode: true                # 侧边栏显示深色模式切换按钮


busuanzi:
  enable: false

cnzz:
  enable: false
  url:                        # 友盟 CNZZ 的 js 代码 src 链接

google_analytics: ""          # Google Analytics 追踪 ID
baidu_analytics: ""           # 百度统计追踪 ID
